application: cabbuddy-1109
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# font-awesome
- url: /(.*\.(woff|ttf))
  static_files: static/\1
  upload: static/(.*\.(woff|ttf))

- url: .*
  script: cabbuddy.wsgi.application

libraries:
- name: django
  version: 1.5

- name: MySQLdb
  version: "latest"

