application: cabbuddy
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: cabbuddy.wsgi.application

libraries:
- name: django
  version: 1.5

- name: MySQLdb
  version: "latest"

